version: "3.3"

services: 
  storage-bridge:
    image: comworkio/storage-bridge:latest
    container_name: storage-bridge
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    networks:
      - storage-bridge
    ports:
      - 8080:8080
      - 8081:8081

networks:
  storage-bridge:
    driver: bridge
