version: "3.3"

services: 
  storage-bridge:
    image: comworkio/storage-bridge:latest
    container_name: storage-bridge
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    networks:
      - storage-bridge
    ports:
      - 8080:8080
  storage-bridge-redis:
    image: redis:6.2.6
    restart: always
    container_name: storage-bridge-redis
    networks:
      - storage-bridge
    volumes:
      - storage-bridge-redis-data:/data

volumes:
  storage-bridge-redis-data:

networks:
  storage-bridge:
    driver: bridge
