version: "3.3"

services: 
  storage-bridge:
    image: comworkio/storage-bridge:${STORAGE_BRIDGE_VERSION}
    container_name: storage-bridge
    env_file: 
      - storage_bridge.env
    networks:
      - storage-bridge
    ports:
      - 7893:8080
  storage-bridge-redis:
    image: redis:6.2.6
    restart: always
    container_name: storage-bridge-redis
    networks:
      - storage-bridge
    volumes:
      - storage-bridge-redis:/data

volumes:
  storage-bridge-redis:

networks:
  storage-bridge:
    driver: bridge
